# Site settings
title: S P Sharan
description: My so-called "About" Page
# baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: S P Sharan
# user_description: I\'m a nomad Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in the <b>crypto-world</b> working for Radix, a London based startup trying to create the next massive scalable DLT. I'm one of the two guys behind all the JS related stuff.
user_description: Just testing this field out. Boooo
user_title: Deep Learning Enthusiast
email: spsharan2000@gmail.com
twitter_username: sharansp2000
github_username:  Syzygianinfern0
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
